apiVersion: apps/v1
kind: Deployment
metadata:
  name: testtobypics
  labels:
    app: tobypics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tobypics
  template:
    metadata:
      labels:
        app: tobypics
    spec:
      containers:
      - name: tobypics
        image: docker.io/gorbot/toby-pictures:latest
        ports:
        - containerPort: 8000
      - name: ebbflow
        image: ebbflow/ebbflow-client-linux-amd64:1.1
        resources:
          requests:
            cpu: 80m
        args:
          - run-blocking
          - --dns
          - toby.pictures
          - --healthcheck-port
          - '8000'
          - --port
          - '8000'
        env:
          - name: EBB_KEY
            valueFrom:
              secretKeyRef:
                name: ebbkey
                key: ebbkey
